const $=s=>document.querySelector(s);let posts=[],current=null,dirty=false,siteConfigured=false;
let locale=selectLocale(localStorage.getItem('seicho-language'),navigator.language);
let theme=selectTheme(localStorage.getItem('seicho-theme'));
function t(key){return translate(locale,key)}
function updateThemeControl(){applyTheme(document.documentElement,theme);$('#theme-icon').textContent=themeIcon(theme);const label=t(theme==='dark'?'switchToLight':'switchToDark');$('#theme-toggle').title=label;$('#theme-toggle').setAttribute('aria-label',label)}
function applyLanguage(){document.documentElement.lang=locale;$('#language').value=locale;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-title]').forEach(el=>el.title=t(el.dataset.i18nTitle));document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));if(!siteConfigured)$('#site-name').textContent=t('siteNotSelected');updateThemeControl();updateCharacterCount();renderList();if(current)render()}
async function api(url,options={}){return requestJSON(fetch,url,options,locale)}
const gitPanel=createGitPanel({api,translate,getLocale:()=>locale,hasUnsavedChanges:()=>dirty});
function showSetup(show=true){setDialogVisible($('#setup'),show);$('#close-setup').classList.toggle('hidden',!siteConfigured)}
async function boot(){applyLanguage();const site=await api('/api/site');siteConfigured=site.configured;$('#app-version').textContent='v'+site.version;if(!site.configured)return showSetup();$('#site-name').textContent=site.path;await loadPosts();await restorePostFromRoute()}
function changeLanguage(e){locale=e.target.value;localStorage.setItem('seicho-language',locale);applyLanguage();gitPanel.render()}$('#language').onchange=changeLanguage;
$('#theme-toggle').onclick=()=>{theme=nextTheme(theme);localStorage.setItem('seicho-theme',theme);updateThemeControl()};
$('#site-form').onsubmit=async e=>{e.preventDefault();const changingSite=siteConfigured;try{const site=await api('/api/site',{method:'POST',body:JSON.stringify({path:$('#site-path').value})});siteConfigured=true;$('#app-version').textContent='v'+site.version;$('#site-name').textContent=site.path;showSetup(false);$('#setup-error').value='';if(changingSite){clearPostRoute(history);showEmptyEditor()}await loadPosts();if(!changingSite)await restorePostFromRoute()}catch(e){$('#setup-error').value=e.message}}
$('#change-site').onclick=()=>showSetup();$('#close-setup').onclick=()=>showSetup(false);
async function loadPosts(){posts=await api('/api/posts');renderList();gitPanel.refresh().catch(()=>{})}
function renderList(){const list=$('#post-list');if(!list)return;const q=$('#search').value,sort=$('#sort').value;list.innerHTML='';filterAndSortPosts(posts,q,sort).forEach(p=>{const el=document.createElement('div');el.className='post'+(current?.path===p.path?' active':'');const updated=new Date(p.modified).toLocaleString(locale==='ja'?'ja-JP':'en-US',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});el.innerHTML=`<strong>${esc(p.title)}${p.draft?'<span class="draft">DRAFT</span>':''}</strong><small>${t('updated')} ${esc(updated)}</small>`;el.onclick=()=>openPost(p.path);list.append(el)})}
$('#sort').value=selectSortOrder(localStorage.getItem('seicho-sort-order'));$('#search').oninput=renderList;$('#sort').onchange=()=>{localStorage.setItem('seicho-sort-order',$('#sort').value);renderList()};
function displayPost(document){current=document;populatePostFields(document,{path:$('#path'),frontMatter:$('#front'),body:$('#body')});updateCharacterCount();dirty=false;showEditor();replacePostRoute(history,current.path);render();renderList()}
async function loadPost(path){displayPost(await api('/api/post?path='+encodeURIComponent(path)))}
async function restorePostFromRoute(){if(!location.pathname.startsWith('/edit/'))return;const path=postPathFromRoute(location.pathname);if(!path||!posts.some(post=>post.path===path)){clearPostRoute(history);toast(t('postNotFound'),true);return}try{await loadPost(path)}catch(e){clearPostRoute(history);toast(e.message,true)}}
function openPost(path){requestDiscard(()=>loadPost(path))}function showEditor(){setEditorVisible($('#editor'),$('#empty'),true)}function showEmptyEditor(){current=null;dirty=false;setEditorVisible($('#editor'),$('#empty'),false)}function showNewPost(show=true){setDialogVisible($('#new-post-modal'),show)}
function openNewPost(){$('#new-post-path').value='posts/new-post.md';$('#new-post-error').value='';showNewPost();setTimeout(()=>{$('#new-post-path').focus();$('#new-post-path').select()},0)}function newPost(){requestDiscard(openNewPost)}
$('#new-post-form').onsubmit=async e=>{e.preventDefault();const path=$('#new-post-path').value.trim();if(!path)return;try{const document=await api('/api/post',{method:'POST',body:JSON.stringify({path})});showNewPost(false);displayPost(document);await loadPosts();$('#body').focus();toast(t('created'))}catch(e){$('#new-post-error').value=e.message}}
$('#close-new-post').onclick=$('#cancel-new-post').onclick=()=>showNewPost(false);$('#new').onclick=$('#empty-new').onclick=newPost;['path','front','body'].forEach(id=>$('#'+id).addEventListener('input',()=>{dirty=true;if(id==='body')updateCharacterCount();render()}));
let renderTimer=0,renderVersion=0;function render(){clearTimeout(renderTimer);const renderLocale=locale,version=++renderVersion;renderTimer=setTimeout(async()=>{try{const result=await api('/api/preview',{method:'POST',body:JSON.stringify({markdown:$('#body').value})});if(version===renderVersion)$('#preview').innerHTML=result.html||`<p style="color:#999">${esc(translate(renderLocale,'previewEmpty'))}</p>`}catch(e){if(version===renderVersion)$('#preview').textContent=translate(renderLocale,'previewError')+': '+e.message}},120)}
function esc(s){return escapeHTML(s)}
$('#save').onclick=save;async function save(){if(!current)return;try{const payload=buildPostPayload({path:$('#path').value,frontMatter:$('#front').value,body:$('#body').value},current);current=await api('/api/post',{method:'PUT',body:JSON.stringify(payload)});$('#path').value=current.path;replacePostRoute(history,current.path);dirty=false;toast(t('saved'));await loadPosts()}catch(e){toast(e.message,true)}}
function updateCharacterCount(){const count=characterLength($('#body').value,locale);$('#character-count').textContent=formatCharacterCount(count,locale)}
let zenMode=false;function setZenMode(enabled){zenMode=enabled;document.body.classList.toggle('zen-mode',enabled);const button=$('#zen-mode');button.dataset.i18n=enabled?'exitZenMode':'zenMode';button.textContent=t(button.dataset.i18n);if(enabled){gitPanel.close();updateCharacterCount();$('#body').focus()}}$('#zen-mode').onclick=()=>setZenMode(!zenMode);
function showDeletePost(show=true){setDialogVisible($('#delete-post-modal'),show)}$('#delete').onclick=()=>{closeDetails($('#post-actions-menu'));if(!current)return;$('#delete-post-path').textContent=current.path;$('#delete-post-error').value='';showDeletePost()}
$('#delete-post-form').onsubmit=async e=>{e.preventDefault();if(!current)return;try{await api('/api/post?path='+encodeURIComponent(current.path),{method:'DELETE'});showDeletePost(false);clearPostRoute(history);showEmptyEditor();await loadPosts();toast(t('deleted'))}catch(e){$('#delete-post-error').value=e.message}}
$('#close-delete-post').onclick=$('#cancel-delete-post').onclick=()=>showDeletePost(false);let pendingDiscardAction=null;function showDiscard(show=true){setDialogVisible($('#discard-modal'),show)}function requestDiscard(action){if(!dirty){action();return}pendingDiscardAction=action;showDiscard()}function cancelDiscard(){pendingDiscardAction=null;showDiscard(false)}
$('#close-discard').onclick=$('#cancel-discard').onclick=cancelDiscard;$('#discard-form').onsubmit=e=>{e.preventDefault();const action=pendingDiscardAction;pendingDiscardAction=null;showDiscard(false);if(action)action()}
document.addEventListener('click',e=>{const menu=$('#post-actions-menu');if(menu.open&&!menu.contains(e.target))closeDetails(menu)});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(!$('#discard-modal').classList.contains('hidden')){cancelDiscard();return}if(!$('#new-post-modal').classList.contains('hidden')){showNewPost(false);return}if(!$('#delete-post-modal').classList.contains('hidden')){showDeletePost(false);return}if(siteConfigured&&!$('#setup').classList.contains('hidden')){showSetup(false);return}if($('#post-actions-menu').open){closeDetails($('#post-actions-menu'));return}if(zenMode)setZenMode(false)});
function toast(msg,bad=false){const el=$('#toast');el.textContent=msg;el.style.background=bad?'#a93e2b':'';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}boot().catch(e=>toast(e.message,true));
