const $=s=>document.querySelector(s);let posts=[],current=null,dirty=false,siteConfigured=false;
const messages={
ja:{language:'言語',closeDialog:'ダイアログを閉じる',close:'閉じる',openHugoSite:'Hugoサイトを開く',siteHelp:'サイト設定ファイルがあるフォルダーの絶対パスを入力してください。',siteFolder:'サイトフォルダー',openSite:'サイトを開く',newPost:'新しい投稿',newPostHelp:'contentフォルダーからの相対パスを入力してください。Hugoのarchetypeを使って作成します。',postPath:'投稿ファイルのパス',cancel:'キャンセル',createPost:'投稿を作成',deleteQuestion:'この投稿を削除しますか？',deleteHelp:'この操作は取り消せません。次のファイルをHugoサイトから削除します。',deletePost:'投稿を削除',unsavedChanges:'保存していない変更があります',unsavedHelp:'このまま移動すると、現在の編集内容は保存されません。',leaveWithoutSaving:'保存せずに移動',returnToEditing:'編集に戻る',siteNotSelected:'サイト未選択',changeSite:'サイト変更',sortPosts:'投稿を並び替え',sortOrder:'投稿の並び順',modifiedNewest:'更新日時が新しい順',modifiedOldest:'更新日時が古い順',dateNewest:'公開日が新しい順',searchPosts:'投稿を検索…',chooseWriting:'文章を書く場所を選びましょう',chooseWritingHelp:'左の一覧から投稿を選ぶか、新しい投稿を作成してください。',deleteThisPost:'この投稿を削除',delete:'削除',save:'保存',zenMode:'Zen Mode',exitZenMode:'Zen Modeを終了',filePath:'ファイルパス',startWriting:'ここから本文を書き始めます…',updated:'更新',created:'Hugoのarchetypeから投稿を作成しました',previewEmpty:'プレビューがここに表示されます。',previewError:'プレビューエラー',saved:'保存しました',deleted:'削除しました'},
en:{language:'Language',closeDialog:'Close dialog',close:'Close',openHugoSite:'Open a Hugo site',siteHelp:'Enter the absolute path to the folder containing your Hugo site configuration.',siteFolder:'Site folder',openSite:'Open site',newPost:'New Post',newPostHelp:'Enter a path relative to the content folder. The post will be created from a Hugo archetype.',postPath:'Post file path',cancel:'Cancel',createPost:'New Post',deleteQuestion:'Delete this post?',deleteHelp:'This action cannot be undone. The following file will be deleted from the Hugo site.',deletePost:'Delete post',unsavedChanges:'You have unsaved changes',unsavedHelp:'Your current edits will not be saved if you continue.',leaveWithoutSaving:'Leave without saving',returnToEditing:'Return to editing',siteNotSelected:'No site selected',changeSite:'Change site',sortPosts:'Sort posts',sortOrder:'Post sort order',modifiedNewest:'Recently modified',modifiedOldest:'Least recently modified',dateNewest:'Newest publication date',searchPosts:'Search posts…',chooseWriting:'Choose something to write',chooseWritingHelp:'Select a post from the list or create a new one.',deleteThisPost:'Delete this post',delete:'Delete',save:'Save',zenMode:'Zen Mode',exitZenMode:'Exit Zen Mode',filePath:'File path',startWriting:'Start writing here…',updated:'Updated',created:'Created the post from a Hugo archetype',previewEmpty:'The preview will appear here.',previewError:'Preview error',saved:'Saved',deleted:'Deleted'}
};
let locale=localStorage.getItem('seicho-language')||((navigator.language||'').toLowerCase().startsWith('ja')?'ja':'en');
function t(key){return messages[locale][key]||key}
function applyLanguage(){document.documentElement.lang=locale;$('#language').value=locale;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-title]').forEach(el=>el.title=t(el.dataset.i18nTitle));document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));if(!siteConfigured)$('#site-name').textContent=t('siteNotSelected');updateCharacterCount();renderList();if(current)render()}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json','Accept-Language':locale,...options.headers}});if(!r.ok){let e=await r.json().catch(()=>({error:r.statusText}));throw Error(e.error)}return r.status===204?null:r.json()}
function showSetup(show=true){$('#setup').classList.toggle('hidden',!show);$('#close-setup').classList.toggle('hidden',!siteConfigured)}
async function boot(){applyLanguage();const site=await api('/api/site');siteConfigured=site.configured;$('#app-version').textContent='v'+site.version;if(!site.configured)return showSetup();$('#site-name').textContent=site.path;await loadPosts()}
function changeLanguage(e){locale=e.target.value;localStorage.setItem('seicho-language',locale);applyLanguage()}$('#language').onchange=changeLanguage;
$('#site-form').onsubmit=async e=>{e.preventDefault();try{const site=await api('/api/site',{method:'POST',body:JSON.stringify({path:$('#site-path').value})});siteConfigured=true;$('#app-version').textContent='v'+site.version;$('#site-name').textContent=site.path;showSetup(false);$('#setup-error').value='';await loadPosts()}catch(e){$('#setup-error').value=e.message}}
$('#change-site').onclick=()=>showSetup();$('#close-setup').onclick=()=>showSetup(false);
async function loadPosts(){posts=await api('/api/posts');renderList()}
function renderList(){const list=$('#post-list');if(!list)return;const q=$('#search').value.toLowerCase(),sort=$('#sort').value;const compare={'modified-desc':(a,b)=>new Date(b.modified)-new Date(a.modified),'modified-asc':(a,b)=>new Date(a.modified)-new Date(b.modified),'date-desc':(a,b)=>(b.date||'').localeCompare(a.date||'')}[sort];list.innerHTML='';posts.filter(p=>(p.title+' '+p.path).toLowerCase().includes(q)).sort((a,b)=>compare(a,b)||a.path.localeCompare(b.path)).forEach(p=>{const el=document.createElement('div');el.className='post'+(current?.path===p.path?' active':'');const updated=new Date(p.modified).toLocaleString(locale==='ja'?'ja-JP':'en-US',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});el.innerHTML=`<strong>${esc(p.title)}${p.draft?'<span class="draft">DRAFT</span>':''}</strong><small>${t('updated')} ${esc(updated)}</small>`;el.onclick=()=>openPost(p.path);list.append(el)})}
$('#search').oninput=renderList;$('#sort').onchange=renderList;
async function loadPost(path){current=await api('/api/post?path='+encodeURIComponent(path));$('#path').value=current.path;$('#front').value=current.frontMatter;$('#body').value=current.body;updateCharacterCount();dirty=false;showEditor();render();renderList()}
function openPost(path){requestDiscard(()=>loadPost(path))}function showEditor(){$('#empty').classList.add('hidden');$('#editor').classList.remove('hidden')}function showNewPost(show=true){$('#new-post-modal').classList.toggle('hidden',!show)}
function openNewPost(){$('#new-post-path').value='posts/new-post.md';$('#new-post-error').value='';showNewPost();setTimeout(()=>{$('#new-post-path').focus();$('#new-post-path').select()},0)}function newPost(){requestDiscard(openNewPost)}
$('#new-post-form').onsubmit=async e=>{e.preventDefault();const path=$('#new-post-path').value.trim();if(!path)return;try{current=await api('/api/post',{method:'POST',body:JSON.stringify({path})});showNewPost(false);$('#path').value=current.path;$('#front').value=current.frontMatter;$('#body').value=current.body;updateCharacterCount();dirty=false;showEditor();render();await loadPosts();$('#body').focus();toast(t('created'))}catch(e){$('#new-post-error').value=e.message}}
$('#close-new-post').onclick=$('#cancel-new-post').onclick=()=>showNewPost(false);$('#new').onclick=$('#empty-new').onclick=newPost;['path','front','body'].forEach(id=>$('#'+id).addEventListener('input',()=>{dirty=true;if(id==='body')updateCharacterCount();render()}));
let renderTimer=0,renderVersion=0;function render(){clearTimeout(renderTimer);const renderLocale=locale,version=++renderVersion;renderTimer=setTimeout(async()=>{try{const result=await api('/api/preview',{method:'POST',body:JSON.stringify({markdown:$('#body').value})});if(version===renderVersion)$('#preview').innerHTML=result.html||`<p style="color:#999">${esc(messages[renderLocale].previewEmpty)}</p>`}catch(e){if(version===renderVersion)$('#preview').textContent=messages[renderLocale].previewError+': '+e.message}},120)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#save').onclick=save;async function save(){if(!current)return;try{current=await api('/api/post',{method:'PUT',body:JSON.stringify({path:$('#path').value,originalPath:current.path,frontMatter:$('#front').value,body:$('#body').value,delimiter:current.delimiter,modified:current.modified})});$('#path').value=current.path;dirty=false;toast(t('saved'));await loadPosts()}catch(e){toast(e.message,true)}}
function updateCharacterCount(){const count=characterLength($('#body').value,locale);$('#character-count').textContent=formatCharacterCount(count,locale)}
let zenMode=false;function setZenMode(enabled){zenMode=enabled;document.body.classList.toggle('zen-mode',enabled);const button=$('#zen-mode');button.dataset.i18n=enabled?'exitZenMode':'zenMode';button.textContent=t(button.dataset.i18n);if(enabled){updateCharacterCount();$('#body').focus()}}$('#zen-mode').onclick=()=>setZenMode(!zenMode);
function showDeletePost(show=true){$('#delete-post-modal').classList.toggle('hidden',!show)}$('#delete').onclick=()=>{if(!current)return;$('#delete-post-path').textContent=current.path;$('#delete-post-error').value='';showDeletePost()}
$('#delete-post-form').onsubmit=async e=>{e.preventDefault();if(!current)return;try{await api('/api/post?path='+encodeURIComponent(current.path),{method:'DELETE'});showDeletePost(false);current=null;dirty=false;$('#editor').classList.add('hidden');$('#empty').classList.remove('hidden');await loadPosts();toast(t('deleted'))}catch(e){$('#delete-post-error').value=e.message}}
$('#close-delete-post').onclick=$('#cancel-delete-post').onclick=()=>showDeletePost(false);let pendingDiscardAction=null;function showDiscard(show=true){$('#discard-modal').classList.toggle('hidden',!show)}function requestDiscard(action){if(!dirty){action();return}pendingDiscardAction=action;showDiscard()}function cancelDiscard(){pendingDiscardAction=null;showDiscard(false)}
$('#close-discard').onclick=$('#cancel-discard').onclick=cancelDiscard;$('#discard-form').onsubmit=e=>{e.preventDefault();const action=pendingDiscardAction;pendingDiscardAction=null;showDiscard(false);if(action)action()}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(!$('#discard-modal').classList.contains('hidden')){cancelDiscard();return}if(!$('#new-post-modal').classList.contains('hidden')){showNewPost(false);return}if(!$('#delete-post-modal').classList.contains('hidden')){showDeletePost(false);return}if(siteConfigured&&!$('#setup').classList.contains('hidden')){showSetup(false);return}if(zenMode)setZenMode(false)});
function toast(msg,bad=false){const el=$('#toast');el.textContent=msg;el.style.background=bad?'#a93e2b':'';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}boot().catch(e=>toast(e.message,true));
